Added while loop to attempt multiple installs and verifications of new version of package from PyPI, so it's more robust.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -146,21 +146,38 @@ jobs:
       - name: Wait for PyPI to update
         run: |
           echo "Waiting for PyPI to update..."
-          sleep 120
+          sleep 60
 
       - name: Install package from PyPI and verify that it matches the new version
         run: |
           python -m pip install --upgrade pip
-          pip install ${{ env.PACKAGE_NAME }}
-          INSTALLED_VERSION=$(pip show ${{ env.PACKAGE_NAME }} | grep Version | cut -d ' ' -f 2)
-          echo "New version: ${{ needs.details.outputs.new_version }}"
-          echo "Installed version: $INSTALLED_VERSION"
-          if [ "$INSTALLED_VERSION" != "${{ needs.details.outputs.new_version }}" ]; then
-            echo "Installed version does not match the new version."
-            exit 1
-          else
-            echo "Installed version matches the new version."
-          fi
+
+          MAX_ATTEMPTS=5
+          ATTEMPT=1
+          WAIT_SECONDS=60
+
+          while [ $ATTEMPT -le $MAX_ATTEMPTS ]
+          do
+            echo "Attempt $ATTEMPT of $MAX_ATTEMPTS to install and verify package version from PyPI..."
+            if ! pip install --upgrade "${{ env.PACKAGE_NAME }}" --timeout $WAIT_SECONDS; then
+              echo "Install failed. Waiting for $WAIT_SECONDS seconds before retrying..."
+              sleep $WAIT_SECONDS
+              continue
+            fi
+            INSTALLED_VERSION=$(pip show ${{ env.PACKAGE_NAME }} | grep Version | cut -d ' ' -f 2)
+            echo "New version: ${{ needs.details.outputs.new_version }}"
+            echo "Installed version: $INSTALLED_VERSION"
+            if [ "$INSTALLED_VERSION" = "${{ needs.details.outputs.new_version }}" ]; then
+              echo "Version from PyPI matched the new version and was successfully installed."
+              exit 0
+            fi
+            echo "New version not yet available on PyPI. Waiting for $WAIT_SECONDS seconds before retrying..."
+            sleep $WAIT_SECONDS
+            ATTEMPT=$((ATTEMPT + 1))
+          done
+
+          echo "Failed to verify package from PyPI after $MAX_ATTEMPTS attempts."
+          exit 1
 
   github_release:
     name: Create GitHub release
